### ISSUE TITLE
scikit-hep metapackage - add function to run all tests of installed org packages

### ISSUE THREAD

**Issue by eduardo-rodrigues** [scikit-hep/scikit-hep#100]
Once this package really is a metapackage we should provide a function `skhep.run_dependencies_tests()` (or alike) to be able to navigate though the installed org packages and run all test suites. This would make sure that the installed versions via the metapackage really are all fine :-).

**Comment by marinang** [comment]
@eduardo-rodrigues I just thought about it right now what about packages that have tests with requirements that are different than the requirements to install. I am thinking about:

* uproot: tests with ROOT
* scikit-stats: tests with zfit (depends on tensorflow)

There are maybe others that I forgot.

**Comment by eduardo-rodrigues** [comment]
It's a good point. We may well need to adapt/improve tests across the board. What I mean is the following: for tests that have special needs, such as ROOT, there should probably be a pytest decorator in the relevant tests to make sure that those tests only run if the requirements are met. Same for certain tests that may only run in Py 3.x and not 2.7. In other terms, there are indeed limitations. It seems to me, though, that we already have limitations in several packages in the sense that not all tests are run for all OS-arch matrix elements. Here we should acknowledge that it will be the same for the tests that are run via scikit-hep.
I don't see an alternative, to be honest. It's the best we can do.

**Comment by eduardo-rodrigues** [comment]
@henryiii, any thoughts on this?

**Comment by eduardo-rodrigues** [comment]
This seems too much. I'm closing this given the more realistic goal achieved with https://github.com/scikit-hep/scikit-hep/issues/108.
