### ISSUE TITLE
Meta discussions and free attribute field

### ISSUE THREAD

**Issue by mayou36** [scikit-hep/scikit-hep#105]
Hey all, two questions: where should we put discussion about scikit-hep packages such as standards or conventions? Is this the right place?

Second: I had several discussions with several people/packages about a "free" (or meta) field; a dict that can store additional information for packages and pass them around. Maybe just as an "experimental" feature to test implementations.
Objects have a dedicated attribute (e.g. `Particle.skhep`) with a dictionary that is meant to be used as e.g. `particle.skhep['zfit'] = {'shape': 'gauss', 'mean': 42}`. (this can oc also be done manually always e.g. by simply setting attributes, so the question is also about the need for it). Creating the dict lazy will also not impact performance if it is not used.

Possible use-cases (biased towards fitting): the particle and generation above, parameters (e.g. additional measurements), additional information for fit results or data objects (e.g. run number, cuts applied).

If several libraries support that, it would be great to converge on a naming convention for the attribute.

Maybe it's also a bad idea, I am not fully convinced, interested to hear some opinions. The alternative is to usually wrap/extend an object, which seems way heavier and maybe often an overkill.

**Comment by eduardo-rodrigues** [comment]
Discussions on project packages: depends whether you want it private or not, etc. If private, then getting in touch via the admins mailing list is the way to go. If public, then either use the Gitter channel or the public forum. All details at https://scikit-hep.org/getting-in-touch :-). The Gitter channel contains more people that the forum, I bet …

**Comment by eduardo-rodrigues** [comment]
@mayou36, apologies that I haven't yet managed to get back to you on those discussions we're having at https://github.com/scikit-hep/decaylanguage/issues/86. But I will … Indeed interesting to hear what others think.

**Comment by eduardo-rodrigues** [comment]
BTW, we're pretty much ready to make a first "test release" of `scikit-hep` as a metapackage. Anyone willing to test it out (probably in a virtual env) once released? That would help me a lot :D. Let me know.

**Comment by eduardo-rodrigues** [comment]
Morning @mayou36! I have worked a couple of things in `DecayLanguage` recently and reread the outstanding issues, which brought me from https://github.com/scikit-hep/decaylanguage/issues/86 to here ... How would you prefer to proceed? A general discussion - see above for your question - could be held on the admins mailing list or, possibly better, on the Gitter channel. As for https://github.com/scikit-hep/decaylanguage/issues/86, we can see how that relates.

I would hence be tempted to close this "issue".

**Comment by mayou36** [comment]
Morning Eduardo, that's good to know! And indeed let's close it ;)

**Comment by eduardo-rodrigues** [comment]
But shall we try and move with https://github.com/scikit-hep/decaylanguage/issues/86 or it's a bad moment for you? In any case I will try and make some comments soon :-).

**Comment by mayou36** [comment]
So I have two large things up currently, so medium well timed, but just go ahead, I'll try to be active again so that we get something out of it. So just ping me ;)
