### ISSUE TITLE
Docker container to be able to test compatibility of all packages?

### ISSUE THREAD

**Issue by eduardo-rodrigues** [scikit-hep/scikit-hep#108]
Following up from the quick chat on Gitter - @matthewfeickert, would it make sense to try and have an environment test in a container to make sure that whatever dependencies we set/update for this (eventually to become) metapackage we are consistent? Maybe there's a simpler way to achieve this and I'm just being naive?

Cc @henryiii as well.

Thanks.

**Comment by matthewfeickert** [comment]
> would it make sense to try and have an environment test in a container to make sure that whatever dependencies we set/update for this (eventually to become) metapackage we are consistent?

Sure. I can just make a Docker image that demos this and also uses the (soon to be **not**-beta) [`2020-resolver` of `pip`](https://discuss.python.org/t/announcement-pip-20-2-release/4863) to make sure everything plays nice.

**Comment by eduardo-rodrigues** [comment]
Brilliant, that would be a game-changer IMO. Thanks!

**Comment by matthewfeickert** [comment]
@eduardo-rodrigues now that I've had a bit of time to think on this I guess I should ask what is the general goal. Is it to see if we at any point try to install all of the libraries in the meta-package from their current release on PyPI if things work? If so, then we could just simply add a nightly CRON job as a GitHub Actions workflow to test this. 

If there is a need for using the Docker image for some sort of distributable testing environment though that could be doable.

**Comment by eduardo-rodrigues** [comment]
It is precisely "to see if we at any point try to install all of the libraries in the meta-package from their current release on PyPI if things work". This is a must, of course. In short, if I do `pip install scikit-hep 1.2.3` I am *assured* that all Scikit-HEP package installed work nicely together

**Comment by matthewfeickert** [comment]
> In short, if I do `pip install scikit-hep 1.2.3` I am _assured_ that all Scikit-HEP package installed work nicely together

This should already be covered by the fact that the 

https://github.com/scikit-hep/scikit-hep/blob/e808b7a01889a06283a53ba752ffe522b938af90/requirements.txt#L1-L10

are restricted to mostly just patch releases so when they are installed in the tests in CI

https://github.com/scikit-hep/scikit-hep/blob/e808b7a01889a06283a53ba752ffe522b938af90/.github/workflows/ci.yml#L26-L29

if they work there they'll continue to work. Though I can start a PR that would add a workflow that would test them at their _current_ release on PyPI (which probably not be the ones installed here) to give an updated warning if things break.
