### ISSUE TITLE
Make metapackage available in conda

### ISSUE THREAD

**Issue by eduardo-rodrigues** [scikit-hep/scikit-hep#131]
We are seeing use-cases already. We first need to get several of the org packages in Conda. List to be added.

**Comment by chrisburr** [comment]
What do you think about dropping the `awkward0`, `uproot3` and `uproot3-methods` dependencies? It requires a non-trivial amount of fiddling to add them to conda-forge for not very much benefit IMHO.

Also requires: https://github.com/conda-forge/staged-recipes/pull/13765

**Comment by chrisburr** [comment]
Done in https://github.com/conda-forge/staged-recipes/pull/13913

**Comment by eduardo-rodrigues** [comment]
Hi @chrisburr, thank you very much for this and apologies for such a late reply!

> What do you think about dropping the awkward0, uproot3 and uproot3-methods dependencies? It requires a non-trivial amount of fiddling to add them to conda-forge for not very much benefit IMHO.

I can well understand that point. But in the end it seems you actually added all of the dependencies of the metapackage to conda? Cool.

I will try and check updates of the dependencies this coming week to get the latest and greatest. Thanks again!

**Comment by chrisburr** [comment]
> seems you actually added all of the dependencies of the metapackage to conda?

Yeah, they were needed for coffea and in general I think it looks like uproot3 is still going to be used for a while given `uproot=4` doesn't support writing yet.
