### ISSUE TITLE
Update package version on CI from release

### ISSUE THREAD

**Issue by andrzejnovak** [scikit-hep/scikit-hep#176]
Should we set up CI to open a PR here every time a "tracked" package publishes a release? Would be a good way to keep this always up to date.

**Comment by eduardo-rodrigues** [comment]
Hi @andrzejnovak, that would be ideal. We would need it to catch minor and major releases of the packages incorporated in this metapackage. Any idea how to get that set up? Help appreciated.

**Comment by andrzejnovak** [comment]
I don't have the experience, but happy to take a look. Seems dependabot could do this for us.

**Comment by eduardo-rodrigues** [comment]
That's very much appreciated 👍.

**Comment by eduardo-rodrigues** [comment]
Close via https://github.com/scikit-hep/scikit-hep/pull/177.
