### ISSUE TITLE
Find a policy for soft imports

### ISSUE THREAD

**Issue by nils-braun** [scikit-hep/scikit-hep#23]
I am just copying the discussion, which was already started by @jpivarski in dependencies.py.
```
# Two ideas:
#
# Strict softimport tries to load at startup (like a normal Python import)
# but hides the fact that it failed until the user tries to use it.
#
# Lazy softimport doesn't even try to load until the user tries to use it.
#
# Both have the same semantics: the user only needs to have installed the
# dependencies he or she will need. But strict puts all the load-time at
# startup while lazy puts all the load-time at first use.
#
# We should have a policy and stick to it. Strict is more typical of Python
# modules, but lazy would spare the user the 1.09 second lag on startup
# if they have ROOT on their system but don't intend to use it in this session.
#
# **Edit:** Another advantage of lazy softimport: if the user tries to use the
# module, it fails with an ImportError, then they install it and try to use
# it again in the same Python session, this will work with lazy softimport
# and not with strict softimport. For this reason, I'm changing the default
# to lazy=True and would advocate that we _only_ do lazy softimports.
```
As this may need some discussion, I am creating an issue here.

I by myself would vote for the strict softimports, because they do not have another "wrapping" layer in between. 
Concerning the ImportError case you discussed in the last paragraph: this is a valid point. However, as this most probably happens in a jupyter notebook, users may already have enabled %load_ext autoreload and do not see this problem (in my experience).
Concerning the import time: this is also a very valid and important point. However, if users do not want to use ROOT functionality, they will probably never import parts of this project, that need ROOT. This assumes that the developers have taken care to really only load ROOT, if it is needed :-)

**Comment by eduardo-rodrigues** [comment]
Closing this since the package will become a metapackage, and the whole structure and submodules will change.
