### ISSUE TITLE
Constants Redundant to scipy.constants

### ISSUE THREAD

**Issue by MarkusPrim** [scikit-hep/scikit-hep#26]
Hi,

I just want to raise awareness to the existing [scipy.constants](https://docs.scipy.org/doc/scipy-0.19.0/reference/constants.html). If constants are implemented here it makes probably more sense to build on the existing ones in scipy.

Cheers,
Markus

**Comment by eduardo-rodrigues** [comment]
There  have been various discussions on this exact point and there are at least issues with what you say:
- scipy uses CODATA that is on the old side.
- All our constants, now in the https://github.com/scikit-hep/hepunits package, are all expressed in the HEP system of units, which is not at all the one of scipy. In the end this latter package does the job albeit in a trivial and really simple way.
