### ISSUE TITLE
Rename main branch "main"

### ISSUE THREAD

**Issue by henryiii** [scikit-hep/scikit-hep#399]
@eduardo-rodrigues, would you mind if I rename the main branches "main" for scikit-hep, hepunits, particle, and decaylanguage? Most of the other projects I work on use "main" now, as does uproot, awkward, etc. It would be nice to be consistent.

**Comment by eduardo-rodrigues** [comment]
Not a problem at all, of course. Thanks.

**Comment by henryiii** [comment]
Done, will do the other ones too. Git's recommendation for local updates:

```bash
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```
