### ISSUE TITLE
Add pytest as a dependency for tests

### ISSUE THREAD

**Issue by henryiii** [scikit-hep/scikit-hep#42]
Pytest is a powerful testing framework, and is far more compact and clear. Project such as Numpy are moving to pytest ([numpy#9362](https://github.com/numpy/numpy/pull/9362), [numpy#9352](https://github.com/numpy/numpy/issues/9352)). Here's an example of pytest:

```python
def test_similar():
    v = 0.1
    assert (v + 0.2) == approx(0.3)
```

The assert gets rewritten to provide nice failure messages when this fails. It's fully backward compatible with nose and unittest, as well, so it would be an easy switch.

It also would only be a dev requirement, obviously.

**Comment by eduardo-rodrigues** [comment]
This is a good idea. The syntax seems nicer indeed. Question is simply whether to move to Pytest now or wait for after the first dev release at the end of this month. Depends on how quickly once can make the move ... Do you want to get started with the migration of the tests for the constants and units modules that are unlikely to be touched in the couple of weeks to come?
