### ISSUE TITLE
minor error in the costheta() function of the Vector3D class

### ISSUE THREAD

**Issue by arx7** [scikit-hep/scikit-hep#56]
The code  read
if self.x == 0 and self.y == 0:
    return 1.
which is not valid  if self.z < 0

**Comment by eduardo-rodrigues** [comment]
Thank you for looking into our package!
We will deal with this in the new year. In any case feel free to submit a pull request. Thanks.

**Comment by eduardo-rodrigues** [comment]
Solved with commit 1f6dfbf.
