### ISSUE TITLE
Use of RDataFrame for RootDataset

### ISSUE THREAD

**Issue by marinang** [scikit-hep/scikit-hep#60]
In the last update of ROOT RDataFrame was introduced, see 

https://root.cern/doc/master/classROOT_1_1RDataFrame.html

https://root-forum.cern.ch/t/rdataframe-a-modern-tool-to-manipulate-and-analyze-root-datasets/29384

I think it could be used for the RootDataset interface when full python support of RDataFrame will be achieved.

**Comment by eduardo-rodrigues** [comment]
As per recent discussions on the future of the package, it is clear that the `RootDataset` class will be removed. This can hence be closed.
