### ISSUE TITLE
Automatically deploy new releases to PyPI

### ISSUE THREAD

**Issue by chrisburr** [scikit-hep/scikit-hep#69]
I'm happy to set this up in the near future to match with most of the organisation's other repositories.

What do you think about having a dedicated account on PyPI for deploying new releases?

**Comment by eduardo-rodrigues** [comment]
Indeed a good idea to have the automatic deployment.

What do you mean by a dedicated account? I confess that I'm using mine for now to make some of the deployments.

**Comment by chrisburr** [comment]
I also use my personal one but my idea was to have a dedicated user so:
 - We don't have to put our personal account's passwords in the CI
 - It's less inconvenient if someone leaves

My suggestion is to make a PyPI account named [`scikit-hep`](https://pypi.org/user/scikit-hep/) which has access to most/all scikit-hep projects.

**Comment by eduardo-rodrigues** [comment]
Kind ping for the email to the admins list :-).

**Comment by eduardo-rodrigues** [comment]
FYI @henryiii I've just tagged v1.0.0 for the first metapackage release and see that it does not get deployed automatically to PyPI. This comment is just to remind ourselves to set things up asap for automatic uploads.

**Comment by eduardo-rodrigues** [comment]
OK, done. Just to be sure - is this issue something you can take care of, @henryiii, as you did it for other Scikit-HEP packages?
