### ISSUE TITLE
NumpyDataset, input from multiple ROOT files / arrays

### ISSUE THREAD

**Issue by marinang** [scikit-hep/scikit-hep#71]
Hi all,

I am using a lot NumpyDataset in my analysis and I encountering a small issue when I want to use a NumpyDataset with inputs from multiple ROOT Files.
When you instantiate a NumpyDataset you give the dataset in the form of a numpy record array or a dictionnary of numpy arrays.
Dealing with several ROOT files I didn't have a problem with **root-numpy**, since It was creating a numpy record array containing all the events from the ROOT files but with **uproot** when you have a lot of root files you do:

`for arrays in uproot.iterate("/set/of/files*.root", treename, ["branch1", "branch2", "branch3"]):`
   `   do_something_with(arrays)`
   `   dataset = NumpyDataset(arrays)`

So I can create a NumpyDataset from each array coming from `uproot.iterate` but cannot merge them with the current version of scikit-hep. 
I have thought of creating a add method for NumpyDataset, but I don't know if it's the best thing to do. Maybe a Fill method? What would be the best (more numpy) way to handle this ? And what about provenances for this case ?

Matt

**Comment by drdavis** [comment]
I've thought about this as well. An idea:

A numpythonic way might be to use `numpy.concatenate`.  Perhaps the use of provenances can be improved (this assumes uniform provenances), but a quick back-of-the-envelope implementation:

```python
def concat(datasets):
    ## should check to make sure datasets is a list of NumpyDataset
    prov = datasets[0]._provenance
    np_concated = np.concatentate([d._data for d in datasets])
    return skhep.datasets.NumpyDataset(np_concated,prov)
```
usage:

```python
datasets = []
for arrays in uproot.iterate("/set/of/files/*.root", treename, ["b1","b2"]):
    do_something(arrays)
    datasets.append(NumpyDataset(arrays)
myDS = skhep.datasets.concat(datasets)
```

**Comment by marinang** [comment]
Solve by #72
