### ISSUE TITLE
Major redesign - package to become a metapackage for Scikit-HEP

### ISSUE THREAD

**Issue by eduardo-rodrigues** [scikit-hep/scikit-hep#86]
The vision for the overall project is for the scikit-hep package to become a metapackage for the Scikit-HEP project. Details can be worked out but the great benefit of having a metapackage is the set-up of scikit-hep tags that define compatible releases of the whole toolset. This is particularly interesting for stacks for experiments - clear what the toolset "scikit-hep version 1.0.0" is - wanted to have stable stacks installable in a simple way. Having a stack defined by a metapackage also helps in analysis preservation matters, widely discussed at present.

**Comment by eduardo-rodrigues** [comment]
FYI @henryiii, @HDembinski and @jpivarski.

I have started cleaning-up this package, removing website-related pages and submodules that are now elsewhere. More to come asap.

**Comment by marinang** [comment]
What about the submodules that are not elsewhere?

**Comment by eduardo-rodrigues** [comment]
Ah, you are too fast, @marinang, I was going to create separate issues for them as we need to discuss a bit more there ;-). They are `dataset`, `modeling` and `visual`.

BTW, I was going to ping you as we need to discuss these matters. I hope you will be available to help.

**Comment by HDembinski** [comment]
Seems like a good idea and strengthens our brand.

**Comment by eduardo-rodrigues** [comment]
For reference we now have a first metapackage release `scikit-hep v1.0.0`, see https://github.com/scikit-hep/scikit-hep/releases/tag/v1.0.0!

The package does still contain some code (see related issues above), and that's the only reason why I'm not closing this just now.

**Comment by eduardo-rodrigues** [comment]
At this point in time only the math module is present, and everything else has either been moved elsewhere or obsoleted. There have also been many metapackage releases in the past year or so. It is time to close the task, even though https://github.com/scikit-hep/scikit-hep/issues/90 will remain open just a little longer in case somebody isn't yet using the vector package or needs some of the geometry related classes and tools available here but not elsewhere.§
