### ISSUE TITLE
Package redesign - future of modeling submodule

### ISSUE THREAD

**Issue by eduardo-rodrigues** [scikit-hep/scikit-hep#88]
As part of a major redesign, see https://github.com/scikit-hep/scikit-hep/issues/86, we need to discuss where the `modeling` submodule could/should go. The module contains the Bayesian blocks algorithm only. There have been some bites of discussion on our Gitter channel concerning a module for statistics-related tools and utilities, and that seems like an appropriate new home.

This needs a discussion with main players - and anyone interested, of course: @HDembinski, @pollackscience and @marinang.

**Comment by HDembinski** [comment]
I am in favor of a statistics related module, which could be just called `statistics` or `stats` if you insist on shorter but less readable names.

**Comment by marinang** [comment]
`scikit-hep/statistics` sounds good, but the problem is the name is already taken in pipy. `skep-statistics' ?
I would also be happy to include what I have done in `lauztat`.

**Comment by eduardo-rodrigues** [comment]
Usual problem … There's a well-known package `statsmodels `so maybe `statsutils`?

@marinang, I was very much hoping you would ;-).

**Comment by marinang** [comment]
No `statsutils` on pipy so it works for me.

**Comment by eduardo-rodrigues** [comment]
@marinang, @HDembinski, shall we try and move forward with a name such as `statutils` or `statsutils`? One could also have `skhep-statistics`, to be used as `from skstats import ...`.
The name can even be changed later before it goes more open … Moving forward would help with the reorganisation, hence my suggestion. What's your take?

**Comment by HDembinski** [comment]
Sorry, for the delay. I don't understand why the name `statistics` has to be available on PyPI? I thought statistics would be a submodule of a scikit-hep module. I thought it would be like `scipy.stats` but `scikithep.stats` or something.

**Comment by HDembinski** [comment]
I like `skhep-statistics` from your choices and `skstats`.

**Comment by HDembinski** [comment]
In summary, if it is possible at all, I would like `skhep.stats` to mimic `scipy.stats`, on PyPI you install `skhep` or `skhep-stats`.

**Comment by marinang** [comment]
@HDembinski it seems you would like to keep a `statistics` submodule inside the `scikit-hep` module whereas @eduardo-rodrigues would like to create a separate module under the `scikit-hep` organisation. Right?

**Comment by eduardo-rodrigues** [comment]
That's right, see the various "issues" created - make scikit-hep a metapackage (exact form to be defined) and have org packages with well-defined stuff, to keep modularity. In that sense, yes, we do want to have a name that is not used in PyPI so far, to be able to pip install. BTW, this does not prevent us from having some import statements defined in scikit-hep at some point in the future, if we ever want to, in which case one could then do from `skhep.units import MeV`, from `skhep.particle import Particle`, etc. But it seems the idea of having it all under a massive single package is not the way forward.

**Comment by HDembinski** [comment]
Ok, then my preference would be (in order) `statutils` or `skhep-statistics`. The version `statsutils` sounds a bit weird to me with the extra "s".

**Comment by eduardo-rodrigues** [comment]
Agreed. I have the same order of preference :-).

**Comment by marinang** [comment]
Same here.

**Comment by marinang** [comment]
So as you may have seen the  package has been created https://github.com/scikit-hep/statutils :)

**Comment by eduardo-rodrigues** [comment]
Thanks @marinang!

@pollackscience, do you want to get started and take your module `skhep.modeling` to this new package? We have to start somewhere ...

**Comment by marinang** [comment]
@eduardo-rodrigues @pollackscience that would be great, then we can discuss in `statutils` the technicalities.

**Comment by eduardo-rodrigues** [comment]
Feel free to suggest a structure as a PR in `statutils` at your best convenience :-).

**Comment by pollackscience** [comment]
Sure, I'll try to do the swap over this week.

**Comment by marinang** [comment]
Unfortunately `statutils` is already registered in pipy. However `statsutils` is not but we don't want that name.
Apparently the name `scikit-stats` is available, but this might not be fair to take that name, idk.

**Comment by marinang** [comment]
`stat-utils` ?

**Comment by eduardo-rodrigues** [comment]
Yeah, this is really annoying that `statutils` is already taken. `stat-utils` is not bad.

I still prefer `scikit-stats`, though, in spite of the responsibility this may bring. This being said, given that you folks are bridging many interesting stat-related business between HEP and data science, maybe that's just a good advert?

@HDembinski and @henryiii, what's your take?

**Comment by pollackscience** [comment]
PR is out, moving the 'modeling' dir to statutils.  As of now, there is no direct dependence on skhep, so the break is clean.  However, it should be noted that my histogram maker in `visual` depends on bayesian blocks for one of it's binning methods.  Because of that, I have not removed anything from the main skhep repo, so this code is essentially duplicated for now.

**Comment by marinang** [comment]
Good :).
We still have the problem of the name though @eduardo-rodrigues @HDembinski  @henryiii

**Comment by HDembinski** [comment]
I prefer prefer `scikit-stats` over `stat-utils`. It somehow sounds more professional.

**Comment by eduardo-rodrigues** [comment]
Let's go for that, then. Pressure is on, with such a name … ;)

**Comment by eduardo-rodrigues** [comment]
@marinang, better reserve the name on PyPI asap.

**Comment by marinang** [comment]
Ok I will do it.

**Comment by marinang** [comment]
Done guys. https://pypi.org/project/scikit-stats/

**Comment by eduardo-rodrigues** [comment]
> PR is out, moving the 'modeling' dir to statutils.  As of now, there is no direct dependence on skhep, so the break is clean.  However, it should be noted that my histogram maker in visual depends on bayesian blocks for one of it's binning methods.  Because of that, I have not removed anything from the main skhep repo, so this code is essentially duplicated for now.

@pollackscience, I guess one needs to get at least a 0.1.0 release of `scikit-stats` to then remove the duplication from `scikit-hep` and make it dependent on `scikit-stats` while the `visual` module is there. Eventually, it will all be somewhere else, and `scikit-hep` will truly become a metapackage.

For you, the main milestone is when the `visual` module will go somewhere else. Let's keep this open until that happens.

**Comment by marinang** [comment]
@eduardo-rodrigues a first release of `scikit-stats` can be published this week or beginning of the next one I think.

**Comment by eduardo-rodrigues** [comment]
OK, cool @marinang. This week would be preferable, just so that we progress with the organisation further :-)

**Comment by eduardo-rodrigues** [comment]
For reference the first release of `scikit-stats` contains the `modeling` submodule from `scikit-hep`, as agreed, see https://github.com/scikit-hep/scikit-stats/releases/tag/v0.1.0.
